here is the erro: Installing devDependencies (npm): - typescript
Error: npm error code ERESOLVE

Error: npm error ERESOLVE could not resolve

Error: npm error
npm error While resolving: @tanstack-query-firebase/react@1.0.6
npm error Found: firebase@10.14.1
npm error node_modules/firebase
npm error   firebase@"^10.12.2" from the root project
npm error
npm error Could not resolve dependency:
npm error peer firebase@"^11.3.0" from @tanstack-query-firebase/react@1.0.6
npm error node_modules/@tanstack-query-firebase/react
npm error   @tanstack-query-firebase/react@"^1.0.5" from the root project
npm error
npm error Conflicting peer dependency: firebase@11.7.1
npm error node_modules/firebase
npm error   peer firebase@"^11.3.0" from @tanstack-query-firebase/react@1.0.6
npm error   node_modules/@tanstack-query-firebase/react
npm error     @tanstack-query-firebase/react@"^1.0.5" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /home/.npm/_logs/2025-05-14T07_54_46_566Z-eresolve-report.txt

Error: npm error A complete log of this run can be found in: /home/.npm/_logs/2025-05-14T07_54_46_566Z-debug-0.log

Error: Failed to install required TypeScript dependencies, please install them manually to continue:
npm install --save-exact --save-dev typescript

Error: { command: 'npm install --save-exact --save-dev typescript' }

[?25h
<IDX> ✘ Preview shutdown unexpectedly